services:
  - type: web
    name: estate-price-prediction
    env: python
    region: frankfurt
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --chdir server server:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
